version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: chore
      include: scope
    schedule:
      interval: "weekly"
