import Footer from "@/components/layout/footer";
import { SiteHeader } from "@/components/layout/header";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const unifontexmono = localFont({
  src: [
    {
      path: "../../public/fonts/UnifontExMono.woff",
      weight: "100 1000",
      style: "normal",
    },
    {
      path: "../../public/fonts/UnifontExMono.woff2",
      weight: "100 1000",
      style: "normal",
    },
  ],
  display: "swap",
  style: "normal",
  variable: "--font-unifontexmono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${unifontexmono.variable} font-sans antialiased`}>
        <SiteHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
